### ISSUE TITLE
为什么安装失败？

### ISSUE THREAD

**Issue by ZhongYi-LinuxDriverDev** [fhyoga/picgo-plugin-watermark#23]
在线安装，安装半天都装不上？？？问题一直解决不了吗？

**Comment by hizablet** [comment]
我这里也显示一直安装中，不知道为什么

**Comment by garryde** [comment]
Apple Silicon
安装不上，一直显示安装中

**Comment by yeungchie** [comment]
![image](https://user-images.githubusercontent.com/30793662/126050676-354aeb10-c896-4d70-b7cc-ff8c0663793c.png)
我也安装失败

**Comment by heyuhengmatt** [comment]
我也安装失败

**Comment by panyanbin** [comment]
安装新版本1.2.0，旧版本依赖python环境导致安装失败

**Comment by garryde** [comment]
![image](https://user-images.githubusercontent.com/14953698/129052835-bdb7e73a-cebb-4fab-9d63-ffa2cfefa734.png)
依然失败

**Comment by panyanbin** [comment]
> ![image](https://user-images.githubusercontent.com/14953698/129052835-bdb7e73a-cebb-4fab-9d63-ffa2cfefa734.png)
> 依然失败

@garryde 你这个应该是网络原因，第三方依赖sharp安装失败，试一试设置阿里镜像。

方式1：添加npm软件包镜像配置
进入picgo目录，运行命令设置npm的软件镜像配置，当然也可以把配置设置到全局`-g`
```
npm config set sharp_binary_host "https://npm.taobao.org/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"
```

方式2：添加环境变量
环境变量npm_config_sharp_binary_host，值为https://npm.taobao.org/mirrors/sharp
环境变量npm_config_sharp_libvips_binary_host，值为https://npm.taobao.org/mirrors/sharp-libvips

**Comment by garryde** [comment]
泻药，人在境外😂

**Comment by garryde** [comment]
> > ![image](https://user-images.githubusercontent.com/14953698/129052835-bdb7e73a-cebb-4fab-9d63-ffa2cfefa734.png)
> > 依然失败
> 
> @garryde 你这个应该是网络原因，第三方依赖sharp安装失败，试一试设置阿里镜像。
> 
> 方式1：添加npm软件包镜像配置
> 进入picgo目录，运行命令设置npm的软件镜像配置，当然也可以把配置设置到全局`-g`
> 
> ```
> npm config set sharp_binary_host "https://npm.taobao.org/mirrors/sharp"
> npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"
> ```
> 
> 方式2：添加环境变量
> 环境变量npm_config_sharp_binary_host，值为https://npm.taobao.org/mirrors/sharp
> 环境变量npm_config_sharp_libvips_binary_host，值为https://npm.taobao.org/mirrors/sharp-libvips

泻药，人在境外😂

**Comment by panyanbin** [comment]
> > > ![image](https://user-images.githubusercontent.com/14953698/129052835-bdb7e73a-cebb-4fab-9d63-ffa2cfefa734.png)
> > > 依然失败
> > 
> > 
> > @garryde 你这个应该是网络原因，第三方依赖sharp安装失败，试一试设置阿里镜像。
> > 方式1：添加npm软件包镜像配置
> > 进入picgo目录，运行命令设置npm的软件镜像配置，当然也可以把配置设置到全局`-g`
> > ```
> > npm config set sharp_binary_host "https://npm.taobao.org/mirrors/sharp"
> > npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 方式2：添加环境变量
> > 环境变量npm_config_sharp_binary_host，值为https://npm.taobao.org/mirrors/sharp
> > 环境变量npm_config_sharp_libvips_binary_host，值为https://npm.taobao.org/mirrors/sharp-libvips
> 
> 泻药，人在境外😂

需要提供一下更多的安装错误信息（picgo插件安装错误日志，npm log安装错误提示信息），或者你可以在picgo的安装目录下，通过npm install命令行方式进行安装，看看是否可以正常安装

**Comment by garryde** [comment]
``> > > > ![image](https://user-images.githubusercontent.com/14953698/129052835-bdb7e73a-cebb-4fab-9d63-ffa2cfefa734.png)
> > > > 依然失败
> > > 
> > > 
> > > @garryde 你这个应该是网络原因，第三方依赖sharp安装失败，试一试设置阿里镜像。
> > > 方式1：添加npm软件包镜像配置
> > > 进入picgo目录，运行命令设置npm的软件镜像配置，当然也可以把配置设置到全局`-g`
> > > ```
> > > npm config set sharp_binary_host "https://npm.taobao.org/mirrors/sharp"
> > > npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 方式2：添加环境变量
> > > 环境变量npm_config_sharp_binary_host，值为https://npm.taobao.org/mirrors/sharp
> > > 环境变量npm_config_sharp_libvips_binary_host，值为https://npm.taobao.org/mirrors/sharp-libvips
> > 
> > 
> > 泻药，人在境外😂
> 
> 需要提供一下更多的安装错误信息（picgo插件安装错误日志，npm log安装错误提示信息），或者你可以在picgo的安装目录下，通过npm install命令行方式进行安装，看看是否可以正常安装

重装2.3.0-bera.7，安装插件显示如下错误
```
2021-08-12 15:04:08 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-08-12 15:05:05 [PicGo ERROR] 插件安装失败，失败码为1，错误日志为[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mpath[0m /Users/garry/Library/Application Support/picgo/node_modules/sharp
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m command failed
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcommand[0m sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m sharp: Using cached /Users/garry/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m   LIBTOOL-STATIC Release/nothing.a
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m   TOUCH Release/obj.target/libvips-cpp.stamp
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m   CXX(target) Release/obj.target/sharp/src/common.o
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info it worked if it ends with ok
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info using node-gyp@7.1.2
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info using node@16.6.1 | darwin | arm64
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info find Python using Python version 3.9.6 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m (node:13777) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m (Use `node --trace-deprecation ...` to show where the warning was created)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args [
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   'binding.gyp',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-f',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   'make',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-I',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/config.gypi',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-I',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-I',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '/Users/garry/Library/Caches/node-gyp/16.6.1/include/node/common.gypi',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dlibrary=shared_library',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dvisibility=default',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dnode_root_dir=/Users/garry/Library/Caches/node-gyp/16.6.1',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dnode_lib_file=/Users/garry/Library/Caches/node-gyp/16.6.1/<(target_arch)/node.lib',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dmodule_root_dir=/Users/garry/Library/Application Support/picgo/node_modules/sharp',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Dnode_engine=v8',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '--depth=.',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '--no-parallel',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '--generator-output',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   'build',
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args   '-Goutput_dir=.'
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args ]
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn make
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include'
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include/glib-2.0'
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/lib/glib-2.0/include'
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m make: *** [Release/obj.target/sharp/src/common.o] Error 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! build error 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! stack Error: `make` failed with exit code: 2
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! System Darwin 20.6.0
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! command "/opt/homebrew/Cellar/node/16.6.1/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! cwd /Users/garry/Library/Application Support/picgo/node_modules/sharp
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! node -v v16.6.1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! node-gyp -v v7.1.2
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m gyp ERR! not ok
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /Users/garry/.npm/_logs/2021-08-12T13_05_05_314Z-debug.log
[0m 

```


有时候显示安装成功，但是并不显示此插件
```
2021-08-12 14:58:49 [PicGo ERROR] startup error
------Error Stack Begin------
Error: Cannot find module '/Users/garry/Library/Application Support/picgo/node_modules/picgo-plugin-watermark'
Require stack:
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/index.js
- /Applications/PicGo.app/Contents/Resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at Object.registerPluginShortKey (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:38601)
    at EventEmitter.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:41305)
-------Error Stack End-------
2021-08-12 14:58:49 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module '/Users/garry/Library/Application Support/picgo/node_modules/picgo-plugin-watermark'
Require stack:
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/index.js
- /Applications/PicGo.app/Contents/Resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:78:26)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:40:43
    at Array.forEach (<anonymous>)
    at PluginHandler.install (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:39:29)
-------Error Stack End------- 
2021-08-12 14:58:49 [PicGo SUCCESS] 插件安装成功 
```

**Comment by panyanbin** [comment]
你电脑是Mac M1吧，这个环境需要编译程序包才行，看错误应该是编译过程出问题，怀疑是通过picgo安装导致无法执行编译。你不要在picgo插件中安装，尝试进入picgo目录通过命令行方式安装。
```
cd /Users/garry/Library/Application Support/picgo
npm install picgo-plugin-watermark
```

如果这个方式还有问题，把输出的npm报错log回复一下。

**Comment by garryde** [comment]
依然报错
```
➜ picgo npm install picgo-plugin-watermark

npm ERR! code 1
npm ERR! path /Users/garry/Library/Application Support/picgo/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Using cached /Users/garry/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! (node:19605) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/garry/Library/Caches/node-gyp/16.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/garry/Library/Caches/node-gyp/16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/garry/Library/Caches/node-gyp/16.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/garry/Library/Application Support/picgo/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include'
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include/glib-2.0'
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/lib/glib-2.0/include'
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/16.6.1/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/garry/Library/Application Support/picgo/node_modules/sharp
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/garry/.npm/_logs/2021-08-12T16_12_17_593Z-debug.log
```

sharp 在m1确实有问题，按照这个页面：https://github.com/lovell/sharp/issues/2460
执行
```
brew install vips
npm install sharp
```
之后安装插件，获得以下报错提示：

```
2021-08-12 18:24:14 [PicGo ERROR] startup error
------Error Stack Begin------
Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node, 1): no suitable image found.  Did find:
	/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node: mach-o, but wrong architecture
	/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node: mach-o, but wrong architecture

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/garry/Library/Application Support/picgo/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/garry/Library/Application Support/picgo/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
-------Error Stack End-------
2021-08-12 18:24:14 [PicGo ERROR] 
------Error Stack Begin------
Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node, 1): no suitable image found.  Did find:
	/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node: mach-o, but wrong architecture
	/Users/garry/Library/Application Support/picgo/node_modules/sharp/build/Release/sharp.node: mach-o, but wrong architecture

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/garry/Library/Application Support/picgo/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/garry/Library/Application Support/picgo/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
-------Error Stack End------- 
2021-08-12 18:24:14 [PicGo SUCCESS] 插件安装成功 
```

按照报错提示操作，依旧
```
- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
```

**Comment by panyanbin** [comment]
apple M1也并不需要额外brew安装依赖，只需要提供Xcode和Python环境依赖即可自动本地构建sharp。

看以下这个报错，怀疑是你的安装路径有空格引起的，正常install sharp后，vendor目录下的相关文件夹肯定是存在的
```
...
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include'
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/include/glib-2.0'
npm ERR! clang: error: no such file or directory: 'Support/picgo/node_modules/sharp/vendor/8.10.6/lib/glib-2.0/include'
....
```

下面的`...Something went wrong installing the "sharp" module...`启动报错就是上一步的sharp构建步骤有问题无法构建引起的

**Comment by dreamhomes** [comment]
更改 Node 版本即可，例如我将 node 降级为 `v10.24.1` 即可成功安装。下载地址：https://nodejs.org/dist/latest-v10.x/  @garryde 

<img width="800" alt="1" src="https://user-images.githubusercontent.com/35626972/133392802-5ade6d23-e6ec-4019-9696-4de35b44c5ad.png">

**Comment by garryde** [comment]
还是不好用，请问你是M1吗？ @dreamhomes

**Comment by love2wind** [comment]
确实不好用，就是装不上，安装成功然后就没有然后了
